<template>
  <div class="w-full flex flex-col items-center justify-center mt-8 lg:mb-12 pb-8 shadow-bottom">
    <div class="w-full 3xl:w-8/12 md:px-8 lg:px-12 xl:px-14 2xl:px-14 3xl:px-0 flex flex-col">
      <h2 class="text-xl text-black font-medium mb-2">
        Inspiración para escapadas futuras
      </h2>
      <Tabs :items="items" :defaultValue="0" :body="body" />
    </div>
  </div>
</template>

<script setup>
import Tabs from "~/components/common/Tabs/Tabs.vue";

const items = [
  "Popular",
  "Arte y Cultura",
  "Al Aire libre",
  "Montañas",
  "Playas",
  "Categorías",
  "Actividades",
];

const body = [
  [
    {
      title: "Canmore",
      subtitle: "Alojamientos vacacionales que admiten mascotas",
    },
    { title: "Benalmádena", subtitle: "Casas vacacionales en la playa" },
    { title: "Marbella", subtitle: "Villas vacacionales" },
    { title: "Mijas", subtitle: "Apartamentos vacacionales" },
    { title: "Prescott", subtitle: "Casas de campo vacacionales" },
    {
      title: "Scottsdale",
      subtitle: "Alojamientos vacacionales que admiten mascotas",
    },
    { title: "Tucson", subtitle: "Alojamientos vacacionales con piscina" },
    { title: "Jasper", subtitle: "Cabañas vacacionales" },
    { title: "Mountain View", subtitle: "Cabañas vacacionales" },
    { title: "Devonport", subtitle: "Casas de campo vacacionales" },
    {
      title: "Mallacoota",
      subtitle: "Alojamientos vacacionales que admiten mascotas",
    },
    { title: "Ibiza", subtitle: "Alquileres vacacionales" },
    { title: "Anaheim", subtitle: "Casas vacacionales" },
    { title: "Monterrey", subtitle: "Bungalows vacacionales" },
    { title: "Paso Robles", subtitle: "Casas vacacionales" },
    { title: "Santa Bárbara", subtitle: "Apartamentos vacacionales" },
    { title: "Sonoma", subtitle: "Cabañas vacacionales" },
    {
      title: "La Serena",
      subtitle: "Alojamientos vacacionales frente a la playa",
    },
    { title: "Dubai", subtitle: "Apartamentos vacacionales" },
    { title: "Birmingham", subtitle: "Casas de campo vacacionales" },
    {
      title: "Brighton",
      subtitle: "Complejos residenciales vacacionales en la playa",
    },
  ],
  [
    { title: "Phoenix", subtitle: "Condominios vacacionales" },
    { title: "Hot Springs", subtitle: "Casas vacacionales" },
    {
      title: "Los Ángeles",
      subtitle: "Alojamientos vacacionales frente a la playa",
    },
    { title: "San Diego", subtitle: "Casas vacacionales" },
    { title: "San Francisco", subtitle: "Alquileres vacacionales" },
    { title: "Barcelona", subtitle: "Alquileres vacacionales" },
    { title: "Praga", subtitle: "Alquileres vacacionales" },
    { title: "Washington", subtitle: "Apartamentos vacacionales" },
    { title: "Keswick", subtitle: "Cabañas vacacionales" },
    { title: "Londres", subtitle: "Apartamentos vacacionales" },
    { title: "Scarborough", subtitle: "Alquileres vacacionales" },
    { title: "Sherwood Forest", subtitle: "Casas de campo vacacionales" },
    { title: "York", subtitle: "Alojamientos vacacionales para familias" },
    { title: "París", subtitle: "Condominios vacacionales" },
    { title: "Rodas", subtitle: "Apartamentos vacacionales" },
    { title: "Nashville", subtitle: "Alquileres vacacionales" },
    { title: "Dublín", subtitle: "Casas de campo vacacionales" },
    { title: "Florencia", subtitle: "Condominios vacacionales" },
    { title: "Roma", subtitle: "Casas vacacionales en la playa" },
    {
      title: "Lisboa",
      subtitle: "Alojamientos vacacionales frente a la playa",
    },
    { title: "Grand Isle", subtitle: "Condominios vacacionales" },
    { title: "Nueva Orleans", subtitle: "Apartamentos vacacionales" },
    { title: "Martha's Vineyard", subtitle: "Alquileres vacacionales" },
    { title: "South Haven", subtitle: "Condominios vacacionales" },
    {
      title: "Duluth",
      subtitle: "Alojamientos vacacionales que admiten mascotas",
    },
    { title: "Ámsterdam", subtitle: "Bungalows vacacionales" },
    { title: "Nueva York", subtitle: "Alquileres vacacionales" },
    { title: "Niza", subtitle: "Apartamentos vacacionales" },
    {
      title: "Inverness",
      subtitle: "Alojamientos vacacionales que admiten mascotas",
    },
  ],
  [
    {
      title: "Lake Martin",
      subtitle: "Alojamientos vacacionales que admiten mascotas",
    },
    { title: "Banff", subtitle: "Casas vacacionales" },
    { title: "Nerja", subtitle: "Apartamentos vacacionales" },
    { title: "Greer", subtitle: "Cabañas vacacionales" },
    { title: "Lake Havasu City", subtitle: "Condominios vacacionales" },
    { title: "Lake Powell", subtitle: "Alquileres vacacionales" },
    { title: "North Rim", subtitle: "Alquileres vacacionales" },
    { title: "Payson", subtitle: "Alquileres vacacionales" },
    { title: "Pinetop-Lakeside", subtitle: "Cabañas vacacionales" },
    { title: "Red Rock", subtitle: "Cabañas vacacionales" },
    {
      title: "Dinner Plain",
      subtitle: "Alojamientos vacacionales que admiten mascotas",
    },
    { title: "Streaky Bay", subtitle: "Alquileres vacacionales" },
    { title: "Emerald Lake", subtitle: "Cabañas vacacionales" },
    { title: "Isla de Vancouver", subtitle: "Condominios vacacionales" },
    { title: "Victoria", subtitle: "Casas de campo vacacionales" },
    { title: "Idyllwild-Pine Cove", subtitle: "Casas vacacionales" },
    { title: "Mammoth Lakes", subtitle: "Alquileres vacacionales" },
    { title: "Palm Desert", subtitle: "Apartamentos vacacionales" },
    { title: "Shaver Lake", subtitle: "Alquileres vacacionales" },
    { title: "South Lake Tahoe", subtitle: "Alquileres vacacionales" },
    { title: "Cultus Lake", subtitle: "Casas de campo vacacionales" },
    { title: "Georgian Bay", subtitle: "Alquileres vacacionales" },
    { title: "Manitoulin Island", subtitle: "Casas de campo vacacionales" },
    { title: "Ottawa River", subtitle: "Casas de campo vacacionales" },
    { title: "The Blue Mountains", subtitle: "Alquileres vacacionales" },
    {
      title: "West Kelowna",
      subtitle: "Alojamientos vacacionales frente a la playa",
    },
    { title: "Gran Canaria", subtitle: "Cabañas vacacionales" },
    { title: "Lanzarote", subtitle: "Alojamientos vacacionales con piscina" },
    { title: "Castle Hill", subtitle: "Alquileres vacacionales" },
    { title: "Aspen", subtitle: "Cabañas vacacionales" },
    { title: "Colorado Springs", subtitle: "Alquileres vacacionales" },
    { title: "Denver", subtitle: "Alquileres vacacionales" },
    { title: "Durango", subtitle: "Condominios vacacionales" },
    { title: "Estes Park", subtitle: "Cabañas vacacionales" },
  ],
  [
    {
      title: "Canmore",
      subtitle: "Alojamientos vacacionales que admiten mascotas",
    },
    { title: "Benalmádena", subtitle: "Casas vacacionales en la playa" },
    { title: "Marbella", subtitle: "Villas vacacionales" },
    { title: "Mijas", subtitle: "Apartamentos vacacionales" },
    { title: "Prescott", subtitle: "Casas de campo vacacionales" },
    {
      title: "Scottsdale",
      subtitle: "Alojamientos vacacionales que admiten mascotas",
    },
    { title: "Tucson", subtitle: "Alojamientos vacacionales con piscina" },
    { title: "Jasper", subtitle: "Cabañas vacacionales" },
    { title: "Mountain View", subtitle: "Cabañas vacacionales" },
    { title: "Devonport", subtitle: "Casas de campo vacacionales" },
    {
      title: "Mallacoota",
      subtitle: "Alojamientos vacacionales que admiten mascotas",
    },
    { title: "Ibiza", subtitle: "Alquileres vacacionales" },
    { title: "Anaheim", subtitle: "Casas vacacionales" },
    { title: "Monterrey", subtitle: "Bungalows vacacionales" },
    { title: "Paso Robles", subtitle: "Casas vacacionales" },
    { title: "Santa Bárbara", subtitle: "Apartamentos vacacionales" },
    { title: "Sonoma", subtitle: "Cabañas vacacionales" },
    {
      title: "La Serena",
      subtitle: "Alojamientos vacacionales frente a la playa",
    },
    { title: "Dubai", subtitle: "Apartamentos vacacionales" },
    { title: "Birmingham", subtitle: "Casas de campo vacacionales" },
    {
      title: "Brighton",
      subtitle: "Complejos residenciales vacacionales en la playa",
    },
  ],
  [
    { title: "Phoenix", subtitle: "Condominios vacacionales" },
    { title: "Hot Springs", subtitle: "Casas vacacionales" },
    {
      title: "Los Ángeles",
      subtitle: "Alojamientos vacacionales frente a la playa",
    },
    { title: "San Diego", subtitle: "Casas vacacionales" },
    { title: "San Francisco", subtitle: "Alquileres vacacionales" },
    { title: "Barcelona", subtitle: "Alquileres vacacionales" },
    { title: "Praga", subtitle: "Alquileres vacacionales" },
    { title: "Washington", subtitle: "Apartamentos vacacionales" },
    { title: "Keswick", subtitle: "Cabañas vacacionales" },
    { title: "Londres", subtitle: "Apartamentos vacacionales" },
    { title: "Scarborough", subtitle: "Alquileres vacacionales" },
    { title: "Sherwood Forest", subtitle: "Casas de campo vacacionales" },
    { title: "York", subtitle: "Alojamientos vacacionales para familias" },
    { title: "París", subtitle: "Condominios vacacionales" },
    { title: "Rodas", subtitle: "Apartamentos vacacionales" },
    { title: "Nashville", subtitle: "Alquileres vacacionales" },
    { title: "Dublín", subtitle: "Casas de campo vacacionales" },
    { title: "Florencia", subtitle: "Condominios vacacionales" },
    { title: "Roma", subtitle: "Casas vacacionales en la playa" },
    {
      title: "Lisboa",
      subtitle: "Alojamientos vacacionales frente a la playa",
    },
    { title: "Grand Isle", subtitle: "Condominios vacacionales" },
    { title: "Nueva Orleans", subtitle: "Apartamentos vacacionales" },
    { title: "Martha's Vineyard", subtitle: "Alquileres vacacionales" },
    { title: "South Haven", subtitle: "Condominios vacacionales" },
    {
      title: "Duluth",
      subtitle: "Alojamientos vacacionales que admiten mascotas",
    },
    { title: "Ámsterdam", subtitle: "Bungalows vacacionales" },
    { title: "Nueva York", subtitle: "Alquileres vacacionales" },
    { title: "Niza", subtitle: "Apartamentos vacacionales" },
    {
      title: "Inverness",
      subtitle: "Alojamientos vacacionales que admiten mascotas",
    },
  ],
  [
    {
      title: "Lake Martin",
      subtitle: "Alojamientos vacacionales que admiten mascotas",
    },
    { title: "Banff", subtitle: "Casas vacacionales" },
    { title: "Nerja", subtitle: "Apartamentos vacacionales" },
    { title: "Greer", subtitle: "Cabañas vacacionales" },
    { title: "Lake Havasu City", subtitle: "Condominios vacacionales" },
    { title: "Lake Powell", subtitle: "Alquileres vacacionales" },
    { title: "North Rim", subtitle: "Alquileres vacacionales" },
    { title: "Payson", subtitle: "Alquileres vacacionales" },
    { title: "Pinetop-Lakeside", subtitle: "Cabañas vacacionales" },
    { title: "Red Rock", subtitle: "Cabañas vacacionales" },
    {
      title: "Dinner Plain",
      subtitle: "Alojamientos vacacionales que admiten mascotas",
    },
    { title: "Streaky Bay", subtitle: "Alquileres vacacionales" },
    { title: "Emerald Lake", subtitle: "Cabañas vacacionales" },
    { title: "Isla de Vancouver", subtitle: "Condominios vacacionales" },
    { title: "Victoria", subtitle: "Casas de campo vacacionales" },
    { title: "Idyllwild-Pine Cove", subtitle: "Casas vacacionales" },
    { title: "Mammoth Lakes", subtitle: "Alquileres vacacionales" },
    { title: "Palm Desert", subtitle: "Apartamentos vacacionales" },
    { title: "Shaver Lake", subtitle: "Alquileres vacacionales" },
    { title: "South Lake Tahoe", subtitle: "Alquileres vacacionales" },
    { title: "Cultus Lake", subtitle: "Casas de campo vacacionales" },
    { title: "Georgian Bay", subtitle: "Alquileres vacacionales" },
    { title: "Manitoulin Island", subtitle: "Casas de campo vacacionales" },
    { title: "Ottawa River", subtitle: "Casas de campo vacacionales" },
    { title: "The Blue Mountains", subtitle: "Alquileres vacacionales" },
    {
      title: "West Kelowna",
      subtitle: "Alojamientos vacacionales frente a la playa",
    },
    { title: "Gran Canaria", subtitle: "Cabañas vacacionales" },
    { title: "Lanzarote", subtitle: "Alojamientos vacacionales con piscina" },
    { title: "Castle Hill", subtitle: "Alquileres vacacionales" },
    { title: "Aspen", subtitle: "Cabañas vacacionales" },
    { title: "Colorado Springs", subtitle: "Alquileres vacacionales" },
    { title: "Denver", subtitle: "Alquileres vacacionales" },
    { title: "Durango", subtitle: "Condominios vacacionales" },
    { title: "Estes Park", subtitle: "Cabañas vacacionales" },
  ],
  [
    {
      title: "The Villages",
      subtitle: "Alojamientos vacacionales que admiten mascotas",
    },
    { title: "Dahlonega", subtitle: "Casas de campo vacacionales" },
    { title: "Creta", subtitle: "Casas de campo vacacionales" },
    { title: "Míkonos", subtitle: "Villas vacacionales" },
    { title: "Santorini", subtitle: "Apartamentos vacacionales" },
    { title: "O‘ahu", subtitle: "Casas vacacionales" },
    { title: "Capri", subtitle: "Apartamentos vacacionales" },
    {
      title: "Bar Harbor",
      subtitle: "Alojamientos vacacionales que admiten mascotas",
    },
    { title: "Mackinac Island", subtitle: "Cabañas vacacionales" },
    { title: "St. Joseph", subtitle: "Condominios vacacionales" },
    { title: "Larsmont", subtitle: "Alquileres vacacionales" },
    { title: "Las Vegas", subtitle: "Alquileres vacacionales" },
    { title: "Madrid", subtitle: "Alquileres vacacionales" },
    { title: "Santa Fe", subtitle: "Apartamentos vacacionales" },
    { title: "Bermagui", subtitle: "Casas vacacionales en la playa" },
    { title: "Evans Head", subtitle: "Alquileres vacacionales" },
    { title: "Sawtell", subtitle: "Casas de campo vacacionales" },
    { title: "Young", subtitle: "Alquileres vacacionales" },
    {
      title: "Ocracoke",
      subtitle: "Alojamientos vacacionales que admiten mascotas",
    },
    { title: "Florencia", subtitle: "Condominios vacacionales" },
    { title: "Lakeside", subtitle: "Casas vacacionales en el lago" },
    { title: "Lincoln City", subtitle: "Alquileres vacacionales" },
    { title: "Paphos", subtitle: "Alquileres vacacionales" },
    { title: "Maleny", subtitle: "Alquileres vacacionales" },
    {
      title: "Stanthorpe",
      subtitle: "Alojamientos vacacionales que admiten mascotas",
    },
    { title: "Newport", subtitle: "Casas vacacionales" },
    { title: "Glasgow", subtitle: "Casas de campo vacacionales" },
    { title: "Scottish Highlands", subtitle: "Alquileres vacacionales" },
  ],
];
</script>
